### ISSUE TITLE
Page: Who

### ISSUE THREAD

**Issue by rowanc1** [ubcgif/geoscixyz-website#2]
![image](https://cloud.githubusercontent.com/assets/913249/14365355/254387d2-fcc2-11e5-8345-4ae0ede4cd72.png)

**Comment by lheagy** [comment]
<img width="1085" alt="geosci 2016-04-13 10-46-42" src="https://cloud.githubusercontent.com/assets/6361812/14503495/2dcf6518-0165-11e6-86d9-8e44dd6518cd.png">
