### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by rowanc1** [ubcgif/geoscixyz-website#3]
@lheagy  do you have a screenshot for this?

**Comment by lheagy** [comment]
<img width="382" alt="geoscilayout ai 40 86 rgb gpu preview 2016-04-06 10-36-36" src="https://cloud.githubusercontent.com/assets/6361812/14365612/95e03232-fcc3-11e5-8107-935c7b9293bc.png">

**Comment by lheagy** [comment]
<img width="1093" alt="geosci 2016-04-13 10-37-48" src="https://cloud.githubusercontent.com/assets/6361812/14503314/7a3dc76a-0164-11e6-9b3f-c083b4bf2f0d.png">
